services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    Pdir\ContentMigrationBundle\Handler\PageExportHandler:
        public: true
        arguments:
            - "@contao.framework"

    Pdir\ContentMigrationBundle\Handler\PageImportHandler:
        public: true
        arguments:
            - "@contao.framework"
            - "@logger"

    Pdir\ContentMigrationBundle\Command\ExportPagesCommand:

    Pdir\ContentMigrationBundle\Command\ExportFormsCommand:

    Pdir\ContentMigrationBundle\Command\ImportCommand:
